/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students implements Serializable {

    private static final long serialVersionUID = 1950763021;

    private Integer       id;
    private String        name;
    private Boolean       sex;
    private LocalDateTime birth;
    private String        phone;
    private String        addr;

    public Students() {}

    public Students(Students value) {
        this.id = value.id;
        this.name = value.name;
        this.sex = value.sex;
        this.birth = value.birth;
        this.phone = value.phone;
        this.addr = value.addr;
    }

    public Students(
        Integer       id,
        String        name,
        Boolean       sex,
        LocalDateTime birth,
        String        phone,
        String        addr
    ) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.birth = birth;
        this.phone = phone;
        this.addr = addr;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getSex() {
        return this.sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    public LocalDateTime getBirth() {
        return this.birth;
    }

    public void setBirth(LocalDateTime birth) {
        this.birth = birth;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddr() {
        return this.addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Students (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);
        sb.append(", ").append(birth);
        sb.append(", ").append(phone);
        sb.append(", ").append(addr);

        sb.append(")");
        return sb.toString();
    }
}
