/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.Students;
import com.generator.tables.records.StudentsRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsDao extends DAOImpl<StudentsRecord, com.generator.tables.pojos.Students, Integer> {

    /**
     * Create a new StudentsDao without any configuration
     */
    public StudentsDao() {
        super(Students.STUDENTS, com.generator.tables.pojos.Students.class);
    }

    /**
     * Create a new StudentsDao with an attached configuration
     */
    public StudentsDao(Configuration configuration) {
        super(Students.STUDENTS, com.generator.tables.pojos.Students.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.generator.tables.pojos.Students object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchById(Integer... values) {
        return fetch(Students.STUDENTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generator.tables.pojos.Students fetchOneById(Integer value) {
        return fetchOne(Students.STUDENTS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchByName(String... values) {
        return fetch(Students.STUDENTS.NAME, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchBySex(Boolean... values) {
        return fetch(Students.STUDENTS.SEX, values);
    }

    /**
     * Fetch records that have <code>birth IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchByBirth(LocalDateTime... values) {
        return fetch(Students.STUDENTS.BIRTH, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchByPhone(String... values) {
        return fetch(Students.STUDENTS.PHONE, values);
    }

    /**
     * Fetch records that have <code>addr IN (values)</code>
     */
    public List<com.generator.tables.pojos.Students> fetchByAddr(String... values) {
        return fetch(Students.STUDENTS.ADDR, values);
    }
}
