/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Students;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studentdb extends SchemaImpl {

    private static final long serialVersionUID = 1979813641;

    /**
     * The reference instance of <code>studentdb</code>
     */
    public static final Studentdb STUDENTDB = new Studentdb();

    /**
     * The table <code>studentdb.students</code>.
     */
    public final Students STUDENTS = com.generator.tables.Students.STUDENTS;

    /**
     * No further instances allowed
     */
    private Studentdb() {
        super("studentdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Students.STUDENTS);
    }
}
