/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Students;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in studentdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>studentdb.students</code>.
     */
    public static final Students STUDENTS = com.generator.tables.Students.STUDENTS;
}
